name: arx-py311
channels:
  - robostack-staging
  - conda-forge
dependencies:
  - python=3.11
  - ros-noetic-kdl-parser
  - cxx-compiler
  - cmake
  - ninja
  - orocos-kdl
  - eigen
  - boost
  - spdlog
  - pybind11
  - numpy
  - click
  - pyzmq