name: arx-py310
channels:
  - robostack-staging
  - conda-forge
dependencies:
  - python=3.10
  - ros-humble-kdl-parser # for python 3.10, slightly different from other python versions
  - ros-humble-ament-cmake
  - cxx-compiler
  - cmake
  - ninja
  - orocos-kdl
  - eigen
  - boost
  - spdlog
  - pybind11
  - numpy
  - click
  - pyzmq
  - pynput
  - pip
  - pip:
      - atomics
      - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz
