name: arx-py310
channels:
  - robostack-staging
  - conda-forge
dependencies:
  - python=3.10
  - ros-humble-kdl-parser # for python 3.10, slightly different from other python versions
  - ros-humble-ament-cmake
  - cxx-compiler
  - cmake
  - ninja
  - orocos-kdl
  - eigen
  - boost
  - spdlog
  - pybind11
  - numpy
  - click
  - pyzmq
  - pynput
  - pip
  - conda-forge::soem # This package is missing in aarch64
  # To install it on aarch64 (arm64), comment out this package and first create the arx-py310 environment.
  # Directly clone the SOEM repository and install it to the conda environment (ensure $CONDA_PREFIX points to arx-py310):
  # `conda activate arx-py310`
  # `git clone https://github.com/OpenEtherCATsociety/SOEM.git && cd SOEM`
  # `mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .. && make -j && make install`
  - pip:
      - atomics
      - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz
